BEGIN;

SET LOCAL search_path = pg_catalog;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE SCHEMA IF NOT EXISTS loteria_numeros;

CREATE TABLE IF NOT EXISTS loteria_numeros.importaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sorteo_id varchar(50) NOT NULL,
    sorteo_nombre varchar(255) NOT NULL,
    fecha_inicio timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin timestamptz,
    estado varchar(20) NOT NULL,
    registros_importados integer NOT NULL DEFAULT 0,
    mensaje_error text,
    tipo_ejecucion varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS loteria_numeros.numeros (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero varchar(5) NOT NULL,
    fracciones integer NOT NULL,
    sorteo_id varchar(50) NOT NULL,
    sorteo_nombre varchar(255) NOT NULL,
    fecha_importacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Compatibilidad con las tablas BIGSERIAL ya existentes en el Supabase central.
ALTER TABLE loteria_numeros.importaciones
    ALTER COLUMN fecha_inicio SET NOT NULL,
    ALTER COLUMN registros_importados SET NOT NULL;
ALTER TABLE loteria_numeros.numeros
    ALTER COLUMN fecha_importacion SET NOT NULL;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_catalog.pg_constraint AS constraint_
          JOIN pg_catalog.pg_class AS relation_
            ON relation_.oid = constraint_.conrelid
          JOIN pg_catalog.pg_namespace AS namespace_
            ON namespace_.oid = relation_.relnamespace
         WHERE namespace_.nspname = 'loteria_numeros'
           AND relation_.relname = 'importaciones'
           AND constraint_.conname = 'importaciones_estado_check'
    ) THEN
        ALTER TABLE loteria_numeros.importaciones
            ADD CONSTRAINT importaciones_estado_check
            CHECK (estado IN ('progreso', 'completada', 'error')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_catalog.pg_constraint AS constraint_
          JOIN pg_catalog.pg_class AS relation_
            ON relation_.oid = constraint_.conrelid
          JOIN pg_catalog.pg_namespace AS namespace_
            ON namespace_.oid = relation_.relnamespace
         WHERE namespace_.nspname = 'loteria_numeros'
           AND relation_.relname = 'importaciones'
           AND constraint_.conname = 'importaciones_tipo_ejecucion_check'
    ) THEN
        ALTER TABLE loteria_numeros.importaciones
            ADD CONSTRAINT importaciones_tipo_ejecucion_check
            CHECK (tipo_ejecucion IN ('manual', 'automatica')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_catalog.pg_constraint AS constraint_
          JOIN pg_catalog.pg_class AS relation_
            ON relation_.oid = constraint_.conrelid
          JOIN pg_catalog.pg_namespace AS namespace_
            ON namespace_.oid = relation_.relnamespace
         WHERE namespace_.nspname = 'loteria_numeros'
           AND relation_.relname = 'importaciones'
           AND constraint_.conname = 'importaciones_registros_check'
    ) THEN
        ALTER TABLE loteria_numeros.importaciones
            ADD CONSTRAINT importaciones_registros_check
            CHECK (registros_importados >= 0) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_catalog.pg_constraint AS constraint_
          JOIN pg_catalog.pg_class AS relation_
            ON relation_.oid = constraint_.conrelid
          JOIN pg_catalog.pg_namespace AS namespace_
            ON namespace_.oid = relation_.relnamespace
         WHERE namespace_.nspname = 'loteria_numeros'
           AND relation_.relname = 'numeros'
           AND constraint_.conname = 'numeros_formato_check'
    ) THEN
        ALTER TABLE loteria_numeros.numeros
            ADD CONSTRAINT numeros_formato_check
            CHECK (numero ~ '^[0-9]{5}$') NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_catalog.pg_constraint AS constraint_
          JOIN pg_catalog.pg_class AS relation_
            ON relation_.oid = constraint_.conrelid
          JOIN pg_catalog.pg_namespace AS namespace_
            ON namespace_.oid = relation_.relnamespace
         WHERE namespace_.nspname = 'loteria_numeros'
           AND relation_.relname = 'numeros'
           AND constraint_.conname = 'numeros_fracciones_check'
    ) THEN
        ALTER TABLE loteria_numeros.numeros
            ADD CONSTRAINT numeros_fracciones_check
            CHECK (fracciones >= 0) NOT VALID;
    END IF;
END
$migration$;

ALTER TABLE loteria_numeros.importaciones
    VALIDATE CONSTRAINT importaciones_estado_check,
    VALIDATE CONSTRAINT importaciones_tipo_ejecucion_check,
    VALIDATE CONSTRAINT importaciones_registros_check;
ALTER TABLE loteria_numeros.numeros
    VALIDATE CONSTRAINT numeros_formato_check,
    VALIDATE CONSTRAINT numeros_fracciones_check;

CREATE INDEX IF NOT EXISTS idx_numeros_numero
    ON loteria_numeros.numeros (numero);
CREATE INDEX IF NOT EXISTS idx_numeros_fracciones
    ON loteria_numeros.numeros (fracciones);
CREATE INDEX IF NOT EXISTS idx_numeros_numero_prefix
    ON loteria_numeros.numeros (numero pg_catalog.text_pattern_ops);
CREATE UNIQUE INDEX IF NOT EXISTS importaciones_una_activa_idx
    ON loteria_numeros.importaciones ((1))
    WHERE estado = 'progreso';

ALTER TABLE loteria_numeros.importaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE loteria_numeros.numeros ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON SCHEMA loteria_numeros
    FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL TABLES IN SCHEMA loteria_numeros
    FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA loteria_numeros
    FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA loteria_numeros
    REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA loteria_numeros
    REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated, service_role;

COMMIT;
